#!/usr/bin/env python3
"""
gen_audio_map.py
────────────────
Scan assets/audio/**/*.mp3 and regenerate src/data/audioAssets.ts.

Metro bundler requires statically-analysable require() paths.

Usage:
  python3 scripts/gen_audio_map.py
"""

from pathlib import Path

ROOT = Path(__file__).parent.parent
AUDIO_DIR = ROOT / "assets" / "audio"
OUT = ROOT / "src" / "data" / "audioAssets.ts"


def main() -> None:
    files = sorted(AUDIO_DIR.rglob("*.mp3"))
    lines = [
        "// Auto-generated by scripts — do not edit manually.",
        "// Re-run: python3 scripts/gen_audio_map.py",
        "//",
        "// Metro bundler requires statically-analysable require() paths.",
        "// This map is the single source of truth for all audio assets.",
        "",
        "const AUDIO_MAP: Record<string, number> = {",
    ]
    for f in files:
        rel = f.relative_to(AUDIO_DIR).as_posix()
        lines.append(f"  '{rel}': require('../../assets/audio/{rel}'),")
    lines.extend(["};", "", "export default AUDIO_MAP;", ""])
    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"✓ Wrote {len(files)} entries → {OUT}")


if __name__ == "__main__":
    main()
