"""
RunCast Audio Generator
-----------------------
Reads clip data from scripts/routes_raw/audio_manifest.json (auto-generated by
extract_audio_manifest.py — run that first if you add new routes).

Two TTS backends:

  ElevenLabs (high quality, requires API key + credits):
    export ELEVENLABS_API_KEY=your_key_here
    python3 generate_audio.py --route sf_embarcadero_loop --mode all

  edge-tts (free, unlimited, Microsoft neural voices, no account needed):
    python3 generate_audio.py --route mumbai_bandra_soul --mode all --backend edge

Special route values:
  --route all     → generate every clip in the manifest
  --route sf      → generate all SF routes
  --route mumbai  → generate all Mumbai routes

Voice mapping per mode:
  history    → George / en-US-GuyNeural       (warm, authoritative)
  food       → Sarah  / en-US-JennyNeural     (warm, professional)
  sightseeing→ Charlie/ en-US-DavisNeural     (energetic)
  local      → Lily   / en-US-AriaNeural      (expressive, conspiratorial)
"""

import os
import sys
import json
import asyncio
import argparse
import re
from pathlib import Path

SCRIPT_DIR = Path(__file__).parent
MANIFEST_PATH = SCRIPT_DIR / "routes_raw" / "audio_manifest.json"
ASSETS_DIR = SCRIPT_DIR.parent / "assets" / "audio"

ELEVENLABS_API_KEY = os.environ.get("ELEVENLABS_API_KEY", "")

# ElevenLabs pre-made voice IDs
VOICE_IDS: dict[str, str] = {
    "history":     "JBFqnCBsd6RMkjVDRZzb",  # George — warm, captivating storyteller
    "food":        "EXAVITQu4vr4xnSDxMaL",  # Sarah — warm, professional
    "sightseeing": "IKne3meq5aSn9XLyUdCD",  # Charlie — deep, confident, energetic
    "local":       "pFZP5JQG7iQjIQuC4Bku",  # Lily — velvety actress, conspiratorial
}

# edge-tts voice names per mode (free, no account needed)
EDGE_VOICE_IDS: dict[str, str] = {
    "history":     "en-US-GuyNeural",
    "food":        "en-US-JennyNeural",
    "sightseeing": "en-US-AndrewNeural",
    "local":       "en-US-AriaNeural",
}

try:
    from elevenlabs.client import ElevenLabs
    from elevenlabs import VoiceSettings
    VOICE_SETTINGS: dict[str, "VoiceSettings"] = {
        "history":     VoiceSettings(stability=0.40, similarity_boost=0.80, style=0.60, use_speaker_boost=True),
        "food":        VoiceSettings(stability=0.30, similarity_boost=0.80, style=0.75, use_speaker_boost=True),
        "sightseeing": VoiceSettings(stability=0.25, similarity_boost=0.80, style=0.80, use_speaker_boost=True),
        "local":       VoiceSettings(stability=0.35, similarity_boost=0.80, style=0.70, use_speaker_boost=True),
    }
    _ELEVENLABS_AVAILABLE = True
except ImportError:
    _ELEVENLABS_AVAILABLE = False
    VOICE_SETTINGS = {}


# ─── Manifest helpers ────────────────────────────────────────────────────────

def load_manifest() -> dict:
    if not MANIFEST_PATH.exists():
        print(f"Error: manifest not found at {MANIFEST_PATH}")
        print("Run first:  python3 scripts/extract_audio_manifest.py")
        sys.exit(1)
    with open(MANIFEST_PATH) as f:
        return json.load(f)


def resolve_clips(manifest: dict, route_arg: str, mode_arg: str) -> list[dict]:
    """Return the list of clip dicts to generate, filtered by route and mode."""
    all_clips  = manifest["clips"]
    routes_idx = manifest["routes"]

    # Determine which audioFile keys to include
    if route_arg == "all":
        keys = list(all_clips.keys())
    elif route_arg == "sf":
        keys = [k for k in all_clips if all_clips[k]["route_id"].startswith("sf_")]
    elif route_arg == "mumbai":
        keys = [k for k in all_clips if all_clips[k]["route_id"].startswith("mumbai_")]
    else:
        if route_arg not in routes_idx:
            print(f"Error: unknown route '{route_arg}'")
            print("Available routes: " + ", ".join(sorted(routes_idx.keys())))
            sys.exit(1)
        keys = routes_idx[route_arg]

    # Filter by mode
    modes = list(VOICE_IDS.keys()) if mode_arg == "all" else [mode_arg]
    return [all_clips[k] for k in keys if all_clips[k]["mode"] in modes]


# ─── TTS backends ────────────────────────────────────────────────────────────

def clean_script_elevenlabs(script: str) -> str:
    return re.sub(r" {2,}", " ", script).strip()


def clean_script_edge(script: str) -> str:
    cleaned = re.sub(r"\[.*?\]", "", script)
    return re.sub(r" {2,}", " ", cleaned).strip()


def generate_clip_elevenlabs(client: "ElevenLabs", script: str, mode: str, output_path: Path) -> bool:
    output_path.parent.mkdir(parents=True, exist_ok=True)
    try:
        print(f"  ⏳ ElevenLabs → {output_path.name}")
        audio = client.text_to_speech.convert(
            voice_id=VOICE_IDS[mode],
            text=clean_script_elevenlabs(script),
            model_id="eleven_multilingual_v2",
            voice_settings=VOICE_SETTINGS[mode],
            output_format="mp3_44100_128",
        )
        with open(output_path, "wb") as f:
            for chunk in audio:
                f.write(chunk)
        print(f"  ✅ {output_path.name}")
        return True
    except Exception as e:
        print(f"  ❌ {output_path.name} — {e}")
        return False


async def _edge_generate(script: str, voice: str, output_path: Path) -> bool:
    try:
        import edge_tts
    except ImportError:
        print("  edge-tts not installed. Run: pip install edge-tts")
        return False
    try:
        communicate = edge_tts.Communicate(script, voice)
        await communicate.save(str(output_path))
        return True
    except Exception as e:
        print(f"  ❌ edge-tts: {output_path.name} — {e}")
        return False


def generate_clip_edge(script: str, mode: str, output_path: Path) -> bool:
    output_path.parent.mkdir(parents=True, exist_ok=True)
    voice = EDGE_VOICE_IDS[mode]
    print(f"  ⏳ edge-tts ({voice}) → {output_path.name}")
    success = asyncio.run(_edge_generate(clean_script_edge(script), voice, output_path))
    if success:
        print(f"  ✅ {output_path.name}")
    return success


# ─── Main ────────────────────────────────────────────────────────────────────

def main():
    manifest    = load_manifest()
    route_ids   = sorted(manifest["routes"].keys())

    parser = argparse.ArgumentParser(description="Generate RunCast audio clips")
    parser.add_argument(
        "--route", default="sf_embarcadero_loop",
        help=(
            "Route ID, or 'all', 'sf', 'mumbai'. "
            "Available: " + ", ".join(route_ids)
        ),
    )
    parser.add_argument("--mode", default="all",
                        choices=["all", "history", "food", "sightseeing", "local"])
    parser.add_argument("--backend", default="elevenlabs",
                        choices=["elevenlabs", "edge"],
                        help="TTS backend: 'elevenlabs' (requires API key) or 'edge' (free)")
    parser.add_argument("--dry-run", action="store_true",
                        help="Print what would be generated without calling the API")
    parser.add_argument("--list", action="store_true",
                        help="List all available routes and clip counts, then exit")
    args = parser.parse_args()

    if args.list:
        print(f"\n{'Route':<42} {'Clips':>5}")
        print("─" * 50)
        for rid in route_ids:
            n = len(manifest["routes"][rid])
            print(f"  {rid:<40} {n:>5}")
        print(f"\n  Total clips in manifest: {len(manifest['clips'])}")
        return

    if args.backend == "elevenlabs":
        if not _ELEVENLABS_AVAILABLE:
            print("Error: elevenlabs package not installed. Run: pip install elevenlabs")
            sys.exit(1)
        if not ELEVENLABS_API_KEY and not args.dry_run:
            print("Error: ELEVENLABS_API_KEY not set.")
            print("  export ELEVENLABS_API_KEY=your_key_here")
            print("  or use --backend edge for free generation")
            sys.exit(1)
        client = ElevenLabs(api_key=ELEVENLABS_API_KEY) if not args.dry_run else None
    else:
        client = None

    clips_to_generate = resolve_clips(manifest, args.route, args.mode)

    if not clips_to_generate:
        print("No clips match the given --route and --mode filters.")
        return

    print(f"\nGenerating {len(clips_to_generate)} clip(s) "
          f"[route={args.route}, mode={args.mode}, backend={args.backend}]\n")

    total = len(clips_to_generate)
    done  = 0
    skip  = 0

    for clip in clips_to_generate:
        out = ASSETS_DIR / clip["audioFile"]

        if out.exists():
            print(f"  ✓ exists: {clip['audioFile']}")
            skip += 1
            done += 1
            continue

        if args.dry_run:
            voice = EDGE_VOICE_IDS[clip["mode"]] if args.backend == "edge" else VOICE_IDS[clip["mode"]]
            print(f"[dry-run] {clip['audioFile']}  ({args.backend} / {voice})")
            print(f"  POI:    {clip['poi_name']}  ({clip['route_id']})")
            print(f"  Script: {clip['script'][:90]}...")
            continue

        if args.backend == "edge":
            ok = generate_clip_edge(clip["script"], clip["mode"], out)
        else:
            ok = generate_clip_elevenlabs(client, clip["script"], clip["mode"], out)

        if ok:
            done += 1

    if not args.dry_run:
        print(f"\n{'='*56}")
        print(f"Done: {done}/{total}  ({skip} already existed, {done - skip} newly generated)")
        if done < total:
            print("Re-run to retry failed clips.")


if __name__ == "__main__":
    main()
